# WorldView Online - Step 1
# Inspect the original WVS Wave 7 RDS file.
# This script does not modify the source data or export participant-level rows.

student_variables <- c(
  "Q165", "Q166", "Q167", "Q168",
  "Q177", "Q178", "Q179", "Q180", "Q181", "Q182", "Q183",
  "Q184", "Q185", "Q186", "Q187", "Q188", "Q189", "Q190",
  "Q191", "Q192", "Q193", "Q194", "Q195",
  "Q260", "Q262", "Q263", "Q275", "Q288", "Q289"
)

country_variables <- c("B_COUNTRY", "B_COUNTRY_ALPHA")
required_variables <- c(country_variables, student_variables)

# Locate the original WVS RDS in the WVS_Dataset subfolder.
preferred_source <- file.path(
  "WVS_Dataset",
  "WVS_Cross-National_Wave_7_rds_v6_0.rds"
)

if (file.exists(preferred_source)) {
  source_path <- preferred_source
} else {
  available_rds <- list.files(
    "WVS_Dataset",
    pattern = "\\.rds$",
    ignore.case = TRUE,
    full.names = TRUE
  )

  # Exclude files generated by WorldView itself.
  candidate_rds <- available_rds[
    !basename(available_rds) %in% c(
      "WVS7_Individual.rds",
      "WVS7_Country.rds"
    )
  ]

  if (length(candidate_rds) == 1L) {
    source_path <- candidate_rds[[1]]
  } else {
    stop(
      paste0(
        "Could not identify one original WVS source RDS in WVS_Dataset. ",
        "Files found: ",
        paste(basename(available_rds), collapse = ", ")
      )
    )
  }
}

cat("WorldView Step 1: inspect the WVS source RDS\n")
cat("Reading:", source_path, "\n\n")

source_data <- readRDS(source_path)

if (!is.data.frame(source_data)) {
  stop("The selected RDS does not contain a data.frame-like object.")
}

output_dir <- file.path(getwd(), "worldview_step1_output")
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

present <- required_variables %in% names(source_data)

variable_presence <- data.frame(
  variable = required_variables,
  required_role = c(
    rep("country identifier", length(country_variables)),
    rep("student variable", length(student_variables))
  ),
  present = present,
  stringsAsFactors = FALSE
)

write.csv(
  variable_presence,
  file.path(output_dir, "variable_presence.csv"),
  row.names = FALSE,
  na = ""
)

missing_variables <- required_variables[!present]

if (length(missing_variables) > 0L) {
  writeLines(
    missing_variables,
    file.path(output_dir, "missing_variables.txt")
  )

  stop(
    paste0(
      "Required variables are missing: ",
      paste(missing_variables, collapse = ", "),
      ". See worldview_step1_output/variable_presence.csv."
    )
  )
}

# Extract the underlying values from haven-labelled vectors without invoking
# the strict haven/vctrs as.numeric() conversion method.
underlying_values <- function(x) {
  if (inherits(x, "haven_labelled")) {
    attributes_to_keep <- attributes(x)[c("names", "dim", "dimnames")]
    attributes(x) <- attributes_to_keep
  }

  x
}

underlying_numeric <- function(x) {
  x <- underlying_values(x)

  if (is.factor(x)) {
    return(as.numeric(x))
  }

  suppressWarnings(as.numeric(x))
}

safe_label <- function(x) {
  value <- attr(x, "label", exact = TRUE)

  if (is.null(value) || length(value) == 0L) {
    return(NA_character_)
  }

  as.character(value[[1]])
}

safe_value_labels <- function(x) {
  labels <- attr(x, "labels", exact = TRUE)

  if (is.null(labels) || length(labels) == 0L) {
    return(NA_character_)
  }

  label_values <- underlying_numeric(labels)
  label_names <- names(labels)

  if (is.null(label_names)) {
    label_names <- rep("", length(label_values))
  }

  paste(
    paste0(label_names, "=", label_values),
    collapse = " | "
  )
}

count_negative_numeric <- function(x) {
  values <- underlying_numeric(x)

  if (length(values) == 0L || all(is.na(values))) {
    return(NA_integer_)
  }

  as.integer(sum(values < 0, na.rm = TRUE))
}

variable_profile <- do.call(
  rbind,
  lapply(required_variables, function(id) {
    x <- source_data[[id]]
    values_numeric <- underlying_numeric(x)
    nonmissing_numeric <- values_numeric[!is.na(values_numeric)]

    data.frame(
      variable = id,
      r_class = paste(class(x), collapse = " "),
      source_label = safe_label(x),
      value_labels = safe_value_labels(x),
      rows = length(x),
      source_NA = sum(is.na(x)),
      negative_numeric_codes = count_negative_numeric(x),
      numeric_min = if (length(nonmissing_numeric) > 0L) {
        min(nonmissing_numeric)
      } else {
        NA_real_
      },
      numeric_max = if (length(nonmissing_numeric) > 0L) {
        max(nonmissing_numeric)
      } else {
        NA_real_
      },
      distinct_nonmissing_numeric = length(unique(nonmissing_numeric)),
      stringsAsFactors = FALSE
    )
  })
)

write.csv(
  variable_profile,
  file.path(output_dir, "variable_profile.csv"),
  row.names = FALSE,
  na = ""
)

country_alpha <- as.character(underlying_values(
  source_data[["B_COUNTRY_ALPHA"]]
))
country_name <- as.character(underlying_values(
  source_data[["B_COUNTRY"]]
))

country_counts <- aggregate(
  rep(1L, nrow(source_data)),
  by = list(
    B_COUNTRY_ALPHA = country_alpha,
    B_COUNTRY = country_name
  ),
  FUN = sum
)

names(country_counts)[3] <- "source_participants"
country_counts <- country_counts[
  order(country_counts$B_COUNTRY_ALPHA, country_counts$B_COUNTRY),
]
row.names(country_counts) <- NULL

write.csv(
  country_counts,
  file.path(output_dir, "country_counts.csv"),
  row.names = FALSE,
  na = ""
)

summary_lines <- c(
  "WorldView Step 1 source inspection",
  paste("Source file:", source_path),
  paste("Rows:", nrow(source_data)),
  paste("Columns:", ncol(source_data)),
  paste(
    "Required variables found:",
    sum(present),
    "of",
    length(required_variables)
  ),
  paste(
    "Countries represented by non-missing alpha code:",
    length(unique(country_alpha[!is.na(country_alpha)]))
  ),
  paste(
    "Countries with more than 1,000 source participants:",
    sum(country_counts$source_participants > 1000, na.rm = TRUE)
  ),
  "",
  "No participant-level rows were written by this inspection script."
)

writeLines(
  summary_lines,
  file.path(output_dir, "inspection_summary.txt")
)

cat("Inspection completed successfully.\n\n")
cat(paste(summary_lines, collapse = "\n"), "\n\n")
cat("Outputs written to:", output_dir, "\n")

